### ISSUE TITLE
Code review - Vortex Labs

### ISSUE THREAD

**Issue by leoarmelin** [lgmacedo/catknow#1]
Thanks for the submission, and great work! Here are some feedback regarding the code:

## /src/models/cat.ts

Even though some 3rd party APIs sucks, it's not a good practice to allow any key in an interface, like `[key: string]: unknown`. This may lead to bad usage and unexpected errors.

## /src/pages/index.tsx

It's nice to pre-fetch data using `getServerSideProps`, but this increase the page loading time. A parallel fetch like `Promise.all` makes things better. If not, decrease the amount of cats images.

The fetch logic is correct, but it seems harder than it should be. Using `useRef` and callbacks inside the page component is not necessary when you are using zustand. You can make your `CatStore` the source of truth.

## /src/pages/cat/[id].tsx

It's recommended to use NextJS `<Image>` component instead of native `<img>` one. [DOCS](https://nextjs.org/docs/app/api-reference/components/image)

**Comment by lgmacedo** [comment]
I opened a PR for this issue. Thank you for the feedback! @leoarmelin
